services:
  library-users-api:
    container_name: library-users-api
    build:
      context: ../../library-users
    ports:
      - "8081:8081"

  library-api:
    container_name: library-api
    build:
      context: ../../library
    ports:
      - "8080:8080"