{
 "title": "Open telemetry",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "UP OTEL Collector",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"otel-collector\"}"
    }
   ]
  },
  {
   "title": "UP Library",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent({exported_job=\"library\"})"
    }
   ]
  },
  {
   "title": "UP Library Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent({exported_job=\"library-users\"})"
    }
   ]
  },
  {
   "title": "UP Library Books",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent({exported_job=\"library-books\"})"
    }
   ]
  },
  {
   "title": "UP Library Loans",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent({exported_job=\"library-loans\"})"
    }
   ]
  },
  {
   "title": "Trace Library users",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "filters": [
      { "id": "8fc7dad7", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "library-api" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Log Library",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service_name=\"library-api\"} | json | line_format `[{{.level}}] {{.body}}`"
    }
   ]
  },
  {
   "title": "Logs Library Users",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{service_name=\"library-users\"} | json | line_format `[{{.level}}] {{.body}}`"
    }
   ]
  },
  {
   "title": "Logs Library Books",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{service_name=\"library-books\"} | json | line_format `[{{.level}}] {{.body}}`"
    }
   ]
  },
  {
   "title": "Logs Library Loans",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{service_name=\"library-loans\"} | json | line_format `[{{.level}}] {{.body}}`"
    }
   ]
  }
 ]
}